export const auth_types = {
    AUTH_START:'AUTH_START',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_FALIURE:'AUTH_FALIURE',
    CHECK_SESSION_START:'CHECK_SESSION_START',
    CHECK_SESSION_SUCCESS:'CHECK_SESSION_SUCCESS',
    CHECK_SESSION_FALIURE:'CHECK_SESSION_FALIURE',
    CLEAR_USER:'CLEAR_USER',
    DELETE_START:'DELETE_START',
    DELETE_SUCCESS:'DELETE_SUCCESS',
    DELETE_FALIURE:'DELETE_FALIURE',
}