export const auth_types = {
    AUTH_START:'AUTH_START',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_FALIURE:'AUTH_FALIURE',
    CHECK_SESSION_START:'CHECK_SESSION_START',
    CHECK_SESSION_SUCCESS:'CHECK_SESSION_SUCCESS',
    CHECK_SESSION_FALIURE:'CHECK_SESSION_FALIURE'
}